//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Курсовая_2 : DbContext
    {
        public Курсовая_2()
            : base("name=Курсовая_2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Заметки> Заметки { get; set; }
        public virtual DbSet<Категория> Категория { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Статуса> Статуса { get; set; }
        public virtual DbSet<ТипУведомлений> ТипУведомлений { get; set; }
        public virtual DbSet<Уведомление> Уведомление { get; set; }
    }
}
