//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заметки
    {
        public decimal ID_Заметки { get; set; }
        public Nullable<int> ID_Категории { get; set; }
        public Nullable<int> ID_Уведомления { get; set; }
        public Nullable<System.DateTime> ДатаСоздания { get; set; }
        public Nullable<System.DateTime> ПлановаяДата { get; set; }
        public string Описание { get; set; }
    
        public virtual Категория Категория { get; set; }
        public virtual Уведомление Уведомление { get; set; }
    }
}
