//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Уведомление
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Уведомление()
        {
            this.Заметки = new HashSet<Заметки>();
        }
    
        public int ID_Уведмоление { get; set; }
        public Nullable<int> ID_ТипУведомления { get; set; }
        public Nullable<int> ID_Сотрудника { get; set; }
        public Nullable<int> ID_Статуса { get; set; }
        public Nullable<System.DateTime> ДатаиВремя { get; set; }
        public Nullable<int> ID_Заказа { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заметки> Заметки { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Статуса Статуса { get; set; }
        public virtual ТипУведомлений ТипУведомлений { get; set; }
    }
}
